INSERT INTO courses_in_ges (courseId, geId) VALUES ("AC ENG 139W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("AFAM 40A","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("AFAM 40A","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("AFAM 40A","VII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("AFAM 40B","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("AFAM 40B","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("AFAM 40B","VII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("AFAM 40C","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("AFAM 40C","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("AFAM 40C","VII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("AFAM 162W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ANTHRO 2A","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ANTHRO 2A","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ANTHRO 2B","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ANTHRO 2C","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ANTHRO 2D","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ANTHRO 10A","VA");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ANTHRO 10B","VA");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ANTHRO 10C","VB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ANTHRO 20A","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ANTHRO 25A","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ANTHRO 25A","VII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ANTHRO 30A","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ANTHRO 41A","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ANTHRO 41A","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ANTHRO 45A","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ANTHRO 48","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ANTHRO 48","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ANTHRO 121AW","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ANTHRO 121D","VII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ANTHRO 125C","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ANTHRO 125X","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ANTHRO 127","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ANTHRO 128B","VII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ANTHRO 134A","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ANTHRO 134G","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ANTHRO 136A","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ANTHRO 136D","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ANTHRO 136K","VII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ANTHRO 162A","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ANTHRO 162B","VII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ANTHRO 163A","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ANTHRO 164A","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ANTHRO 164P","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ANTHRO 180AW","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ANTHRO H190W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ARABIC 1C","VI");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ARABIC 2A","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ARABIC 2B","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ARABIC 2C","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ARABIC 51","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ARABIC 51","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ARMN 1C","VI");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ARMN 2A","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ARMN 2B","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ARMN 2C","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ART 1A","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ART 1B","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ART 1C","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ART 8","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ART 9A","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ART 9B","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ART 9C","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ART 12A","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ART 12B","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ART 12C","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ART 101W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ART 115W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ART HIS 30","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ART HIS 30","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ART HIS 40A","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ART HIS 40A","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ART HIS 40B","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ART HIS 40B","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ART HIS 40C","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ART HIS 40C","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ART HIS 42A","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ART HIS 42A","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ART HIS 42B","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ART HIS 42B","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ART HIS 42C","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ART HIS 42C","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ART HIS 42D","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ART HIS 42D","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ART HIS 42E","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ART HIS 42E","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ART HIS 44","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ART HIS 44","VII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ART HIS 55","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ART HIS 55","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ART HIS 190W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ARTS 1","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ARTS H81","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ASIANAM 50","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ASIANAM 50","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ASIANAM 50","VII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ASIANAM 51","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ASIANAM 51","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ASIANAM 51","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ASIANAM 52","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ASIANAM 52","VII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ASIANAM 53","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ASIANAM 53","VII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ASIANAM 54","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ASIANAM 54","VII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ASIANAM 55","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ASIANAM 55","VII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ASIANAM 100W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ASIANAM 130","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ASIANAM 130","VII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ASIANAM 144","VII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("BIO SCI 1A","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("BIO SCI 6","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("BIO SCI 9A","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("BIO SCI 9B","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("BIO SCI 9E","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("BIO SCI 9G","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("BIO SCI 9J","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("BIO SCI 9K","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("BIO SCI 10","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("BIO SCI 12","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("BIO SCI 17","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("BIO SCI 23","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("BIO SCI 35","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("BIO SCI 36","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("BIO SCI 37","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("BIO SCI 38","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("BIO SCI 41","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("BIO SCI 43","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("BIO SCI 44","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("BIO SCI 45","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("BIO SCI 47","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("BIO SCI 55","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("BIO SCI 56","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("BIO SCI 75","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("BIO SCI H90","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("BIO SCI 93","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("BIO SCI H93","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("BIO SCI 94","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("BIO SCI H94","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("BIO SCI E106L","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("BIO SCI D111L","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("BIO SCI E112L","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("BIO SCI N113L","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("BIO SCI M114L","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("BIO SCI E115L","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("BIO SCI M116L","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("BIO SCI M118L","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("BIO SCI N118","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("BIO SCI M121L","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("BIO SCI N123L","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("BIO SCI M130L","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("BIO SCI E131L","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("BIO SCI E140L","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("BIO SCI E142W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("BIO SCI E160L","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("BIO SCI E166L","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("BIO SCI E179L","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("BIO SCI E186L","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("BIO SCI 191CW","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("BIO SCI 199W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("BME 3","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("BME 3","VA");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CHC/LAT 61","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CHC/LAT 61","VII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CHC/LAT 62","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CHC/LAT 62","VII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CHC/LAT 63","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CHC/LAT 63","VII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CHC/LAT 64","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CHC/LAT 64","VII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CHC/LAT 65","VII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CHC/LAT H80","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CHC/LAT 102W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CHC/LAT 120","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CHC/LAT 124W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CHC/LAT 148W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CHC/LAT 151","VII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CHC/LAT 154","VII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CHC/LAT 156W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CHC/LAT 161","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CHC/LAT 163","VII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CHC/LAT 164A","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CHC/LAT 164A","VII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CHC/LAT 167","VII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CHC/LAT 168","VII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CHC/LAT 176","VII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CHC/LAT 178","VII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CHC/LAT 178A","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CHC/LAT 183","VII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CHC/LAT H190W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CHEM 1A","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CHEM 1A","VA");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CHEM 1B","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CHEM 1B","VA");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CHEM 1C","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CHEM 1C","VA");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CHEM H2A","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CHEM H2A","VA");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CHEM H2B","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CHEM H2B","VA");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CHEM H2C","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CHEM H2C","VA");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CHEM M2A","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CHEM M2A","VA");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CHEM M2B","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CHEM M2B","VA");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CHEM M2C","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CHEM M2C","VA");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CHEM M3C","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CHEM M3C","VA");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CHEM 12","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CHEM 12","VA");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CHEM 14","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CHEM 14","VA");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CHEM H90","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CHEM H90","VA");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CHEM 101W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CHEM 177L","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CHEM 180W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CHEM H181W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CHINESE 1C","VI");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CHINESE 1MC","VI");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CHINESE S1BC","VI");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CHINESE 2A","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CHINESE 2B","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CHINESE 2C","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CHINESE 2MA","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CHINESE 2MB","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CHINESE 2MC","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CHINESE 3A","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CHINESE 3B","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CHINESE 3C","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CHINESE 40","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CLASSIC 36A","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CLASSIC 36B","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CLASSIC 36C","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CLASSIC 37A","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CLASSIC 37B","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CLASSIC 37C","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CLASSIC 45A","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CLASSIC 45B","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CLASSIC 45C","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CLASSIC 160W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("COM LIT 3","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("COM LIT 3","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("COM LIT 8","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("COM LIT 9","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("COM LIT 9","VII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("COM LIT 10","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("COM LIT 10","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("COM LIT 60A","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("COM LIT 60A","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("COM LIT 60B","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("COM LIT 60B","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("COM LIT 60C","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("COM LIT 60C","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("COM LIT 101W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("COM LIT 102W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("COM LIT 190W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CRM/LAW C7","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CRM/LAW C10","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CRM/LAW H80","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CRM/LAW C169W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CRM/LAW C183","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CRM/LAW C187","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("CRM/LAW C187","VII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("DANCE 3","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("DANCE 80","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("DANCE 80","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("DANCE 81","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("DANCE 90A","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("DANCE 90A","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("DANCE 90B","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("DANCE 90B","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("DANCE 90C","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("DANCE 185W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("DRAMA 10","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("DRAMA 11","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("DRAMA 15","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("DRAMA 16","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("DRAMA 20A","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("DRAMA 20B","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("DRAMA 20C","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("DRAMA 40A","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("DRAMA 40A","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("DRAMA 40B","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("DRAMA 40B","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("DRAMA 40C","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("DRAMA 40C","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("DRAMA 109W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("DRAMA 110W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("DRAMA 112W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("DRAMA 116W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("DRAMA 118W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("DRAMA 126W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("DRAMA 129W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("DRAMA 180W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("EARTHSS 1","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("EARTHSS 1","VA");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("EARTHSS 3","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("EARTHSS 3","VA");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("EARTHSS 5","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("EARTHSS 5","VA");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("EARTHSS 7","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("EARTHSS 7","VA");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("EARTHSS 15","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("EARTHSS 15","VA");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("EARTHSS 15","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("EARTHSS 17","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("EARTHSS 17","VA");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("EARTHSS 17","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("EARTHSS 19","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("EARTHSS 19","VB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("EARTHSS 21","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("EARTHSS 21","VA");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("EARTHSS 21","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("EARTHSS 23","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("EARTHSS 23","VA");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("EARTHSS 23","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("EARTHSS 27","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("EARTHSS 27","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("EARTHSS 40A","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("EARTHSS 40A","VA");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("EARTHSS 40B","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("EARTHSS 40C","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("EARTHSS 40C","VA");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("EARTHSS 176W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("EARTHSS 177W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("EARTHSS 190CW","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("EARTHSS 198W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("EARTHSS H198","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("EAS 20","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("EAS 20","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("EAS 40","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("EAS 40","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("EAS 55","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("EAS 55","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("EAS H84","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("EAS 192W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ECON 1","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ECON 11","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ECON 11","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ECON 13","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ECON 13","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ECON 15A","VA");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ECON 15B","VA");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ECON 17","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ECON 20A","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ECON 20B","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ECON 23","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ECON 122CW","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ECON 123CW","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ECON 137W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ECON 142CW","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ECON 145FW","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ECON 149W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ECON 153W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ECON 164AW","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ECON 190BW","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("EDUC 10","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("EDUC 15","VA");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("EDUC 25","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("EDUC 30","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("EDUC 40","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("EDUC 55","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("EDUC 124","VII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("EDUC 143AW","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("EDUC 143BW","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("EDUC 143BW","VII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("EDUC 179W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ENGLISH 8","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ENGLISH 8","VII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ENGLISH 9","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ENGLISH 10","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ENGLISH 10B","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ENGLISH 11","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ENGLISH 11","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ENGLISH 11C","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ENGLISH 11C","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ENGLISH 12","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ENGLISH 16","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ENGLISH 17","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ENGLISH H80","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ENGLISH H80","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ENGLISH H81","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ENGLISH 101W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ENGR 1A","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ENGR 190W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ENGR 196W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ENGR H196W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ENGRCEE 40","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ENGRCEE 60","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("EURO ST 9","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("EURO ST 9","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("EURO ST 10","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("EURO ST 10","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("EURO ST 10","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("EURO ST S10","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("EURO ST S10","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("EURO ST S10","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("EURO ST 11","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("EURO ST 11","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("EURO ST 11","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("EURO ST S11","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("EURO ST S11","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("EURO ST S11","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("EURO ST 12","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("EURO ST 12","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("EURO ST 12","VB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("EURO ST 13","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("EURO ST 13","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("EURO ST 190W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("FLM&MDA H80","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("FLM&MDA H80","VII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("FLM&MDA 85A","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("FLM&MDA 85B","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("FLM&MDA 85C","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("FLM&MDA 139W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("FRENCH 1BC","VI");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("FRENCH 1BCSP","VI");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("FRENCH 1C","VI");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("FRENCH S1BC","VI");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("FRENCH 2A","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("FRENCH 2AB","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("FRENCH 2B","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("FRENCH 2BC","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("FRENCH 2C","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("FRENCH S2AB","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("FRENCH S2BC","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("FRENCH 50","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("FRENCH 50","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("FRENCH 139W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("GDIM 25","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("GDIM 31","VA");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("GDIM 32","VA");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("GDIM 41","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("GEN&SEX 20","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("GEN&SEX 20","VII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("GEN&SEX 50A","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("GEN&SEX 50A","VII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("GEN&SEX 50B","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("GEN&SEX 50B","VII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("GEN&SEX 50C","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("GEN&SEX 50C","VII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("GEN&SEX 60A","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("GEN&SEX 60B","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("GEN&SEX 60C","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("GEN&SEX 60C","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("GERMAN 1BC","VI");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("GERMAN 1C","VI");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("GERMAN S1BC","VI");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("GERMAN 2A","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("GERMAN 2B","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("GERMAN 2C","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("GERMAN 140W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("GERMAN 160W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("GERMAN 170W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("GLBL ME 60A","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("GLBL ME 60A","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("GLBL ME 60B","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("GLBL ME 60B","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("GLBL ME 60C","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("GLBL ME 60C","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("GLBL ME 100W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("GREEK 1C","VI");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("HEBREW 50","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("HEBREW 50","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("HISTORY 5","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("HISTORY 10","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("HISTORY 10","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("HISTORY 11","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("HISTORY 11","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("HISTORY 12","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("HISTORY 15A","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("HISTORY 15A","VII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("HISTORY 15C","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("HISTORY 15C","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("HISTORY 15C","VII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("HISTORY 15D","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("HISTORY 15D","VII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("HISTORY 15F","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("HISTORY 15F","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("HISTORY 15F","VII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("HISTORY 15G","VII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("HISTORY 16A","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("HISTORY 16A","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("HISTORY 16B","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("HISTORY 16B","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("HISTORY 16C","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("HISTORY 16C","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("HISTORY 18A","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("HISTORY 18A","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("HISTORY 21A","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("HISTORY 21A","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("HISTORY 21B","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("HISTORY 21B","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("HISTORY 21C","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("HISTORY 21C","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("HISTORY 36A","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("HISTORY 36B","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("HISTORY 36C","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("HISTORY 37A","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("HISTORY 37B","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("HISTORY 37C","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("HISTORY 40A","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("HISTORY 40B","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("HISTORY 40C","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("HISTORY 50","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("HISTORY 50","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("HISTORY 60","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("HISTORY 60","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("HISTORY 70A","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("HISTORY 70A","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("HISTORY 70B","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("HISTORY 70B","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("HISTORY 70C","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("HISTORY 70D","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("HISTORY 70D","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("HISTORY 70E","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("HISTORY 70E","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("HISTORY 70F","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("HISTORY 70F","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("HISTORY 100W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("HISTORY 149","VII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("HUMAN 1A","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("HUMAN 1AS","IA");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("HUMAN 1B","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("HUMAN 1BES","IA");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("HUMAN 1BS","IA");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("HUMAN 1C","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("HUMAN 1C","VII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("HUMAN 1C","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("HUMAN 1CS","IA");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("HUMAN B1A","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("HUMAN H1AS","IA");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("HUMAN H1BS","IA");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("HUMAN H1CS","IA");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("HUMAN 10","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("HUMAN 10","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("HUMAN H80","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("HUMAN H81","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("HUMAN H81","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("HUMAN H83","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("HUMAN H84","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("HUMAN H142W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("I&C SCI 3","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("I&C SCI 4","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("I&C SCI 5","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("I&C SCI 6B","VB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("I&C SCI 6D","VB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("I&C SCI 6N","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("I&C SCI 6N","VB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("I&C SCI 7","VA");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("I&C SCI 10","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("I&C SCI 11","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("I&C SCI 11","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("I&C SCI 31","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("I&C SCI 31","VB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("I&C SCI 32","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("I&C SCI 32","VA");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("I&C SCI 32","VB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("I&C SCI 32A","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("I&C SCI 32A","VA");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("I&C SCI 32A","VB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("I&C SCI 33","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("I&C SCI 33","VB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("I&C SCI 46","VB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("I&C SCI 51","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("I&C SCI 60","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("I&C SCI 61","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("I&C SCI 139W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("IN4MATX 12","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("IN4MATX 12","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("IN4MATX H81","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("IN4MATX 162W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("INTL ST 1","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("INTL ST 1","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("INTL ST 11","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("INTL ST 11","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("INTL ST 12","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("INTL ST 12","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("INTL ST 13","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("INTL ST 13","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("INTL ST 14","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("INTL ST 14","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("INTL ST 15","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("INTL ST 15","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("INTL ST 16","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("INTL ST 16","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("INTL ST 17","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("INTL ST 17","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("INTL ST 104BW","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("INTL ST 122","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("INTL ST 145A","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("INTL ST 147CW","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("INTL ST 148W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("INTL ST 154W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("INTL ST 158B","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("INTL ST 162B","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("INTL ST 183CW","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("INTL ST 183E","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ITALIAN 1BC","VI");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ITALIAN 1BCSP","VI");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ITALIAN 1C","VI");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ITALIAN 2A","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ITALIAN 2B","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ITALIAN 2C","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ITALIAN 50","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("ITALIAN 50","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("JAPANSE 1C","VI");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("JAPANSE S1BC","VI");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("JAPANSE 2A","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("JAPANSE 2B","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("JAPANSE 2C","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("JAPANSE S2AB","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("JAPANSE S2BC","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("JAPANSE 3A","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("JAPANSE 3B","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("JAPANSE 3C","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("KOREAN 1C","VI");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("KOREAN 1KC","VI");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("KOREAN S1BC","VI");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("KOREAN 2A","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("KOREAN 2B","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("KOREAN 2C","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("KOREAN 2KA","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("KOREAN 2KB","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("KOREAN 2KC","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("KOREAN 3A","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("KOREAN 3B","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("KOREAN 3C","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("LATIN 1C","VI");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("LIT JRN 20","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("LIT JRN 101BW","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("LPS 29","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("LPS 29","VB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("LPS 30","VB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("LPS 31","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("LPS 31","VA");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("LPS 40","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("LPS 60","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("LPS 60","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("LPS H80","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("LPS H81","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("LPS 91","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("LPS H91","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("LPS H91","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("LPS H95","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("LPS 100W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("LPS H123","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("LPS H125","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("LPS 142W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("LSCI 1","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("LSCI 2","VII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("LSCI 3","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("LSCI 3","VB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("LSCI 10","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("LSCI 10","VB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("LSCI 20","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("LSCI 20","VB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("LSCI 43","VB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("LSCI 51","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("LSCI 68","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("LSCI 195W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("MATH 2A","VB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("MATH 2B","VB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("MATH 2D","VB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("MATH H2D","VB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("MATH 3A","VB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("MATH 5A","VB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("MATH 5B","VB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("MATH 7A","VB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("MATH 7B","VB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("MATH 9","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("MATH 9","VB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("MATH 10","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("MATH 10","VB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("MATH 195W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("MED HUM 1","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("MED HUM 1","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("MED HUM 3","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("MED HUM 3","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("MGMT 4A","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("MGMT 4B","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("MGMT 7","VA");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("MGMT 111","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("MGMT 128","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("MGMT 191W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("MUSIC 3","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("MUSIC 4","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("MUSIC 5","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("MUSIC 8","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("MUSIC 9","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("MUSIC 25","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("MUSIC 40B","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("MUSIC 40B","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("MUSIC 40C","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("MUSIC 40C","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("MUSIC 40D","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("MUSIC 40D","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("MUSIC 41","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("MUSIC 42","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("MUSIC 42","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("MUSIC 44","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("MUSIC 44","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("MUSIC 45","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("MUSIC 46","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("MUSIC 47","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("MUSIC 48","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("MUSIC 51","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("MUSIC 78","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("MUSIC 78","VII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("MUSIC H80","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("MUSIC 142W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("MUSIC 143W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("MUSIC 144W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("MUSIC 145W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("NUR SCI 110W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("NUR SCI 179AW","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PERSIAN 1C","VI");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PERSIAN 2A","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PERSIAN 2B","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PERSIAN 2C","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PERSIAN 50","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PERSIAN 50","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PHILOS 1","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PHILOS 2","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PHILOS 2","VB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PHILOS 3","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PHILOS 4","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PHILOS 5","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PHILOS 7","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PHILOS 10","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PHILOS 11","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PHILOS 12","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PHILOS 13","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PHILOS 21","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PHILOS 22","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PHILOS 29","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PHILOS 29","VB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PHILOS 30","VB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PHILOS 31","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PHILOS 31","VA");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PHILOS 91","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PHILOS 100W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PHILOS 102W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PHILOS 142W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PHRMSCI H80","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PHRMSCI 174L","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PHRMSCI 177L","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PHY SCI 139W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PHYSICS 3A","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PHYSICS 3A","VA");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PHYSICS 3B","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PHYSICS 3B","VA");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PHYSICS 3C","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PHYSICS 3C","VA");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PHYSICS 7C","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PHYSICS 7C","VA");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PHYSICS 7D","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PHYSICS 7D","VA");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PHYSICS 7E","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PHYSICS 7E","VA");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PHYSICS 12","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PHYSICS 12","VA");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PHYSICS 14","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PHYSICS 14","VA");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PHYSICS 15","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PHYSICS 17","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PHYSICS 18","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PHYSICS 19","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PHYSICS 20A","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PHYSICS 20A","VA");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PHYSICS 20B","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PHYSICS 20B","VA");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PHYSICS 20D","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PHYSICS 20D","VA");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PHYSICS 20E","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PHYSICS 20E","VA");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PHYSICS 21","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PHYSICS H80","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PHYSICS H90","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PHYSICS H90","VA");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PHYSICS 106W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PHYSICS 121W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("POL SCI 10A","VA");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("POL SCI 10B","VA");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("POL SCI 10C","VB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("POL SCI 11A","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("POL SCI 11A","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("POL SCI 11C","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("POL SCI 21A","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("POL SCI 31A","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("POL SCI 32A","VII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("POL SCI 41A","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("POL SCI 41A","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("POL SCI 44B","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("POL SCI 44B","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("POL SCI 45A","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("POL SCI 45A","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("POL SCI 51A","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("POL SCI 51A","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("POL SCI 61A","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("POL SCI 61A","VII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("POL SCI 71A","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("POL SCI H80","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("POL SCI H80","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("POL SCI 121HW","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("POL SCI 122BW","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("POL SCI 124A","VII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("POL SCI 124B","VII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("POL SCI 125CW","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("POL SCI 126C","VII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("POL SCI 128BW","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("POL SCI 136BW","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("POL SCI 137BW","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("POL SCI 138AW","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("POL SCI 138CW","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("POL SCI 138DW","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("POL SCI 141B","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("POL SCI 141C","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("POL SCI 147CW","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("POL SCI 147E","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("POL SCI 154F","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("POL SCI 154G","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("POL SCI 154KW","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("POL SCI 171AW","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("POL SCI 171CW","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("POL SCI 172A","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("POL SCI 174CW","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("POL SCI 190W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PSCI 9","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PSCI 11A","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PSCI 11B","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PSCI 11C","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PSCI 111W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PSCI 192Q","VII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PSCI 192S","VII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PSYCH 7A","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PSYCH 9A","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PSYCH 9B","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PSYCH 9C","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PSYCH 10A","VA");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PSYCH 10B","VA");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PSYCH 10C","VB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PSYCH 21A","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PSYCH 46A","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PSYCH 56L","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PSYCH 78A","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PSYCH 111BW","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PSYCH 112BW","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PSYCH 122P","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PSYCH 146MW","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PUBHLTH 1","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PUBHLTH 2","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PUBHLTH 7A","VA");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PUBHLTH 7B","VA");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PUBHLTH 30","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PUBHLTH 60","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PUBHLTH 80","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PUBHLTH 90","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PUBHLTH 168","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PUBHLTH 170","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PUBHLTH 174","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("PUBHLTH 195W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("REL STD 5A","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("REL STD 5A","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("REL STD 5B","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("REL STD 5B","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("REL STD 5C","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("REL STD 5C","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("REL STD 17","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("REL STD 21","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("REL STD 61","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("REL STD 61","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("REL STD 110W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("RUSSIAN 1C","VI");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("RUSSIAN 2A","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("RUSSIAN 2B","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("RUSSIAN 2C","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("RUSSIAN 50","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("RUSSIAN 50","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOC SCI 1A","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOC SCI H1E","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOC SCI H1F","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOC SCI H1G","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOC SCI 2A","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOC SCI 4A","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOC SCI 4A","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOC SCI 5A","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOC SCI 5D","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOC SCI 5D","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOC SCI 10A","VA");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOC SCI 10B","VA");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOC SCI 10C","VB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOC SCI 11A","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOC SCI 11A","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOC SCI 12","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOC SCI 12","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOC SCI 15","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOC SCI 15","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOC SCI 16","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOC SCI 16","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOC SCI 17","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOC SCI 17","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOC SCI 40","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOC SCI 70C","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOC SCI 70C","VII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOC SCI 78A","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOC SCI 78A","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOC SCI 78A","VII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOC SCI 78B","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOC SCI 78B","VII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOC SCI 78C","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOC SCI 78C","VII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOC SCI 132","VII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOC SCI 133","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOC SCI 134W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOC SCI 172AW","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOC SCI 173L","VII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOC SCI 183CW","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOC SCI 183E","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOC SCI 184GW","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOC SCI 185W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOC SCI H190C","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOC SCI 193CW","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOCECOL 13","VA");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOCECOL H20A","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOCECOL H20B","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOCECOL H20C","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOCECOL 104W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOCECOL 106W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOCECOL 111W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOCECOL E127","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOCECOL 183CW","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOCECOL 186CW","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOCECOL H190W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOCECOL 194W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOCECOL 195CW","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOCECOL 195W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOCIOL 1","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOCIOL 1","VII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOCIOL 2","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOCIOL 2","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOCIOL 3","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOCIOL 3","VII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOCIOL 10A","VA");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOCIOL 10B","VA");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOCIOL 10C","VB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOCIOL 31","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOCIOL 44","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOCIOL 51","VII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOCIOL 62","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOCIOL 63","VII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOCIOL 64","VII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOCIOL 68A","VII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOCIOL 120W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOCIOL 154W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOCIOL 155BW","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOCIOL 157AW","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOCIOL 158CW","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOCIOL 161W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOCIOL 164W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOCIOL 167AW","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOCIOL 173W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOCIOL 177C","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOCIOL 177C","VII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOCIOL 177W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOCIOL 180AW","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SOCIOL 188BW","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SPANISH 1C","VI");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SPANISH S1BC","VI");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SPANISH 2A","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SPANISH 2AB","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SPANISH 2B","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SPANISH 2C","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SPANISH S2AB","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SPANISH S2BC","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SPANISH 3","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SPANISH 3H","VII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SPANISH 50","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SPANISH 50","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SPANISH 60E","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SPANISH 60E","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SPANISH 60S","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SPANISH 60S","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SPANISH 61","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SPANISH 61","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SPANISH 62","VII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SPPS 40","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SPPS 70A","VII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SPPS H190C","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("SPPS 193CW","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("STATS 7","VA");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("STATS 8","VA");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("STATS 67","VA");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("UNI STU 13C","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("UNI STU H30A","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("UNI STU H30A","VA");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("UNI STU H30B","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("UNI STU H30B","VB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("UNI STU H30C","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("UNI STU H30D","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("UNI STU H30E","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("UNI STU H30F","II");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("UNI STU H80","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("UNI STU 85A","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("UNI STU 85B","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("UNI STU 85C","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("UPPP 4","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("UPPP 5","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("UPPP 8","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("UPPP 114W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("UPPP 142","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("UPPP 166","III");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("UPPP 172","VII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("VIETMSE 1C","VI");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("VIETMSE 2A","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("VIETMSE 2B","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("VIETMSE 2C","VIII");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("VIETMSE 50","IV");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("WRITING 30","IA");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("WRITING 31","IA");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("WRITING 37","IA");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("WRITING 39B","IA");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("WRITING 39C","IA");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("WRITING 101W","IB");
INSERT INTO courses_in_ges (courseId, geId) VALUES ("WRITING 139W","IB");
